version: "3"
services:
  b-api:
    build: .
    ports:
      - "1323:1323"
      - "2345:2345"
    depends_on:
      - db
    volumes:
      - ./app:/go/src/app
    tty: true
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=bowling_score
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --innodb_file_per_table
      --innodb_file_format=BARRACUDA
      --innodb_large_prefix=1
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql

  b-api-ui:
    image: redocly/redoc
    container_name: "b-api-ui"
    ports:
      - "8082:80"
    volumes:
      - ./openapi/dist:/usr/share/nginx/html/api
    environment:
      SPEC_URL: api/swagger.yaml

  swagger-merger:
    build:
      context: .
      dockerfile: ./openapi/Dockerfile
    command: >
      watch 'swagger-merger -i /swagger/src/index.yaml -o /swagger/dist/swagger.yaml' /swagger/src/
    volumes:
      - ./openapi:/swagger