auth:
  $ref: "./auth.yaml"
user:
  $ref: "./user.yaml"
user_detail:
  $ref: "./user_detail.yaml"

delete:
  $ref: "./delete.yaml"
notFoundError:
  $ref: "./notFoundError.yaml"
internalError:
  $ref: "./internalError.yaml"