auth:
  $ref: "./auth.yaml"
user:
  $ref: "./user.yaml"
user_detail:
  $ref: "./user_detail.yaml"
user_post:
  $ref: "./user_post.yaml"

notFoundError:
  $ref: "./notFoundError.yaml"
internalError:
  $ref: "./internalError.yaml"